# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 437edc94715e112cbdbad67fd23c5df2d1e3e91595f83323c57336c670cdbe058673dbf14d9d66e2a05ccf55e97d43a2951c2ee3337ed6c8298b6f4da5d5584e

test:
  secret_key_base: 5d82b5bd997fbcb8b150f3fac5191bb211bab954151f7ca9c0e475bd6908ab7d2949a68915dbbf628d3f075ded6a1bcfb40050caac5b54c2e37d0d49fc43d3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
